version: "3"

services:
    php-apache:
        image: geerlingguy/php-apache:latest
        container_name: foxstrcount
        ports:
            - "8080:80"
        restart: always
        volumes:
            - ./:/var/www/html:rw,delegated
        command: ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
